name: ${project.artifactId}
description: ${project.description}
main: ${project.mainclass}
version: ${project.version}
author: Mitsugaru
depend: [Vault]
#THIS PLUGIN WAS UPDATED BY IAMCION!
#As this plugin has been abandoned, iamcion has brought it back to life!
#thank him by subscribing! - www.youtube.com/user/iamcion

commands:
  wc:
    description: Root command

permissions:
  WorldChannels.colorize:
    description: Can use chat colors.
    default: op
  WorldChannels.shout:
    description: Speak to all players on the server
    default: op
  WorldChannels.observe:
    description: Listen to all worlds
    default: op
  WorldChannels.observe.auto:
    description: Automatically listen to all worlds on join
    default: op
  WorldChannels.admin:
    description: Administrate plugin
    default: op
