name: WorldChannels
main: com.mitsugaru.WorldChannels.WorldChannels
description: Plugin to support per world chat configuration.
version: 0.143
author: Mitsugaru
depend: [Vault]

commands:
  wc:
    description: Root command

permissions:
  WorldChannels.colorize:
    description: Can use chat colors.
    default: op
  WorldChannels.shout:
    description: Speak to all players on the server
    default: op
  WorldChannels.observe:
    description: Listen to all worlds
    default: op
  WorldChannels.observe.auto:
    description: Automatically listen to all worlds on join
    default: op
  WorldChannels.admin:
    description: Administrate plugin
    default: op